# Generated by Django 3.1.1 on 2020-09-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourses',
            old_name='courname',
            new_name='coursename',
        ),
    ]
