# Generated by Django 3.1.1 on 2020-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200921_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='instructorLed',
            new_name='ct',
        ),
        migrations.RemoveField(
            model_name='details',
            name='selfPaced',
        ),
        migrations.AddField(
            model_name='details',
            name='your_Choice',
            field=models.BooleanField(default=False),
        ),
    ]
