# Generated by Django 3.1.1 on 2020-09-22 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20200921_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 17, 46, 53, 697140, tzinfo=utc), verbose_name='started from'),
            preserve_default=False,
        ),
    ]
