# Generated by Django 3.1.1 on 2020-09-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='imagename',
            field=models.ImageField(default='test', upload_to='images/'),
        ),
    ]
