# Generated by Django 3.1.1 on 2020-09-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_allcourses_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='summary',
            field=models.CharField(default='test1', max_length=500),
        ),
    ]
