# Generated by Django 3.1.1 on 2020-09-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_details_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='summary',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='summary',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='allcourses',
            name='imagename',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
