# Generated by Django 3.1.2 on 2020-10-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20200928_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
