# Generated by Django 3.1.2 on 2020-10-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20201022_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='email',
            field=models.CharField(default='', max_length=500),
        ),
    ]
