# Generated by Django 3.1.2 on 2020-10-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20201022_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='allcourses',
            name='email',
        ),
        migrations.RemoveField(
            model_name='allcourses',
            name='role',
        ),
    ]
