# Generated by Django 3.1.2 on 2020-10-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20201022_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='ProfileCreate',
        ),
    ]
