# Generated by Django 3.1.2 on 2020-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20201022_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_NAME', models.CharField(default='', max_length=100)),
                ('ASSET_DESC', models.CharField(default='', max_length=200)),
                ('CATEGORY_LKUP_TYP', models.CharField(default='', max_length=200)),
                ('CATEGORY_LKUP_CD', models.CharField(default='', max_length=200)),
                ('SUB_CATEGORY_LKUP_TYP', models.CharField(default='', max_length=200)),
                ('SUB_CATEGORY_LKUP_CD', models.CharField(default='', max_length=200)),
                ('REC_EFFT_START_DT', models.DateTimeField(verbose_name='Started from ')),
                ('REC_EFFT_END_DT', models.DateTimeField(verbose_name='Ended Time')),
                ('REC_ACTV_INDC', models.CharField(default='', max_length=200)),
                ('ASSET_SOURCE_INFO', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileCreate',
        ),
    ]
