# Generated by Django 3.1.2 on 2020-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20201028_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_master',
            name='REC_EFFT_END_DT',
            field=models.DateField(verbose_name='Ended Time'),
        ),
        migrations.AlterField(
            model_name='asset_master',
            name='REC_EFFT_START_DT',
            field=models.DateField(verbose_name='Started from '),
        ),
    ]
