# Generated by Django 3.1.2 on 2020-10-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_auto_20201028_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Master1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_NAME', models.CharField(choices=[('Financial Report', 'Financial Report'), ('Operations Report', 'Operations Report'), ('HR Report', 'HR Report'), ('Reporting Report', 'Reporting Report'), ('SDR Report', 'SDR Report')], max_length=200)),
            ],
        ),
    ]
