# Generated by Django 3.1.2 on 2020-10-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_reference_data_lookup_report_agency_mapping_user_profile_user_role_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_master1',
            old_name='ASSET_NAME',
            new_name='Category',
        ),
    ]
