# Generated by Django 3.1.2 on 2020-11-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20201029_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset_Master',
        ),
        migrations.DeleteModel(
            name='Asset_Master1',
        ),
        migrations.DeleteModel(
            name='Report_Agency_Mapping',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.DeleteModel(
            name='User_Role_Mapping',
        ),
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REC_EFFT_END_DT',
            field=models.DateField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REC_EFFT_START_DT',
            field=models.DateField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REFNC_LKUP_CD',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REFNC_LKUP_TYPE',
            field=models.CharField(default='', max_length=100),
        ),
    ]
