# Generated by Django 3.1.2 on 2020-11-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_auto_20201101_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_NAME', models.CharField(default='', max_length=100)),
                ('ASSET_DESC', models.CharField(default='', max_length=200)),
                ('CATEGORY_LKUP_TYP', models.CharField(default='', max_length=200)),
                ('CATEGORY_LKUP_CD', models.CharField(default='', max_length=200)),
                ('SUB_CATEGORY_LKUP_TYP', models.CharField(default='', max_length=200)),
                ('SUB_CATEGORY_LKUP_CD', models.CharField(default='', max_length=200)),
                ('REC_EFFT_START_DT', models.DateField(verbose_name='Started from ')),
                ('REC_EFFT_END_DT', models.DateField(verbose_name='Ended Time')),
                ('REC_ACTV_INDC', models.CharField(default='', max_length=200)),
                ('ASSET_SOURCE_INFO', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Agency_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPORT_ID', models.CharField(default='', max_length=200)),
                ('PARENT_REFNC_TYP', models.CharField(default='', max_length=200)),
                ('PARENT_REFNC_CD', models.CharField(default='', max_length=200)),
                ('SUB_AGENCY_REFNC_TYP', models.CharField(default='', max_length=200)),
                ('SUB_AGENCY_REFNC_CD', models.CharField(default='', max_length=200)),
                ('ROLE_LKUP_TYPE', models.CharField(default='', max_length=200)),
                ('ROLE_LKUP_CD', models.CharField(default='', max_length=200)),
                ('REC_EFFT_START_DT', models.DateField(verbose_name='Started from ')),
                ('REC_EFFT_END_DT', models.DateField(verbose_name='Ended Time')),
                ('REC_ACTV_INDC', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(default='', max_length=200)),
                ('USER_FRST_NM', models.CharField(default='', max_length=200)),
                ('USER_LAST_NM', models.CharField(default='', max_length=200)),
                ('USER_MIDLLE_NAME', models.CharField(default='', max_length=200)),
                ('USER_NM', models.CharField(default='', max_length=200)),
                ('EMAIL_ID', models.CharField(default='', max_length=200)),
                ('REC_EFFT_START_DT', models.DateField(verbose_name='Started from ')),
                ('REC_EFFT_END_DT', models.DateField(verbose_name='Ended Time')),
                ('REC_ACTV_INDC', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Role_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(default='', max_length=200)),
                ('ROLE_LKUP_TYPE', models.CharField(default='', max_length=200)),
                ('ROLE_LKUP_CD', models.CharField(default='', max_length=200)),
                ('REC_EFFT_START_DT', models.DateField(verbose_name='Started from ')),
                ('REC_EFFT_END_DT', models.DateField(verbose_name='Ended Time')),
                ('REC_ACTV_INDC', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
