# Generated by Django 3.1.2 on 2020-11-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_asset_master_report_agency_mapping_user_profile_user_role_mapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset_Master',
            new_name='Asset_Master1',
        ),
    ]
