# Generated by Django 3.1.2 on 2020-11-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_auto_20201101_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset_Master1',
        ),
        migrations.DeleteModel(
            name='Report_Agency_Mapping',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.DeleteModel(
            name='User_Role_Mapping',
        ),
    ]
