# Generated by Django 3.1.2 on 2020-11-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
