# Generated by Django 3.1.2 on 2020-11-04 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_delete_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REC_EFFT_END_DT',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 4, 13, 23, 49, 603010)),
        ),
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REC_EFFT_START_DT',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 4, 13, 23, 49, 603010)),
        ),
    ]
