# Generated by Django 3.1.2 on 2020-11-04 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_auto_20201104_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REC_EFFT_END_DT',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 4, 15, 56, 29, 379661)),
        ),
        migrations.AlterField(
            model_name='reference_data_lookup',
            name='REC_EFFT_START_DT',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 4, 15, 56, 29, 379661)),
        ),
    ]
